### ISSUE TITLE
Support for Debian 10

### ISSUE THREAD

**Issue by mdular** [elastic/puppet-elasticsearch#1057]
* Module version: 6.4, any recent
* Puppet version: 5.5.10
* OS and version: Debian 10

## Feature request

Debian 10 is unsupported currently. Is there any intention of changing that?
It mostly seems like some bad upper version constraints on puppetlabs-stdlib and puppetlabs-concat by yum modules, which in turn are required by elastic_stack.

**Comment by c33s** [comment]
anyone know how to get the 6.0/6.4 branch (puppet 4 compat) up and running with debian10? it is really hard to debug. debian9 and debian10 are not really that different. there was no issue with debian9 but in debian10 the systemd service for the created index is missing.  if i follow the setup manually from the official docs i get an instance up and running https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html. 

using this module leads to the following error and no startup script for `myindexname`
```
Error: Could not prefetch elasticsearch_index provider 'ruby': Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
==> myindexname: Error: Failed to apply catalog: Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
---

the autocompetion for the service is not working but it only autocompletes for `elasticsearch` which is masked but not for the service for the index.
if started manually by indexname `service elasticsearch-myindexname start` it leads to an error
```
root@stage:/usr/lib/systemd/system# service elasticsearch-myindexname status
* elasticsearch-myindexname.service - Elasticsearch instance myindexname
   Loaded: loaded (/lib/systemd/system/elasticsearch-myindexname.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-12-09 03:19:35 CET; 14s ago
     Docs: http://www.elastic.co
  Process: 3986 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p /var/run/elasticsearch/elasticsearch-myindexname.pid --quiet (code=exited, status=1/FAILURE)
 Main PID: 3986 (code=exited, status=1/FAILURE)

Dec 09 03:19:35 stage elasticsearch[3986]: Unrecognized VM option 'PrintGCDateStamps'
Dec 09 03:19:35 stage elasticsearch[3986]: Error: Could not create the Java Virtual Machine.
Dec 09 03:19:35 stage elasticsearch[3986]: Error: A fatal exception has occurred. Program will exit.
Dec 09 03:19:35 stage elasticsearch[3986]:         at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:126)
Dec 09 03:19:35 stage elasticsearch[3986]:         at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
Dec 09 03:19:35 stage elasticsearch[3986]:         at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
Dec 09 03:19:35 stage elasticsearch[3986]:         at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
Dec 09 03:19:35 stage elasticsearch[3986]:         at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Dec 09 03:19:35 stage systemd[1]: elasticsearch-myindexname.service: Main process exited, code=exited, status=1/FAILURE
Dec 09 03:19:35 stage systemd[1]: elasticsearch-myindexname.service: Failed with result 'exit-code'.
```

removing the `PrintGCDateStamps` flag allows the start `service elasticsearch-myindexname start`

**Comment by c33s** [comment]
puppet run without errors on debian10 and elasticsearch 7.10.0 with the following config:

host-hiera:
```yaml
elasticsearch::version: false
elasticsearch::repo_version: 7.x
elasticsearch::jvm_options:
- '11:-XX:+UseG1GC'
- '11:-XX:InitiatingHeapOccupancyPercent=75'
- '8:-XX:+PrintGCApplicationStoppedTime'
- '8:-XX:+PrintGCDateStamps'
- '8:-XX:+PrintTenuringDistribution'
- '8:-XX:+UseCMSInitiatingOccupancyOnly'
- '8:-XX:+UseConcMarkSweepGC'
- '8:-XX:+UseGCLogFileRotation'
- '8:-XX:GCLogFileSize=64m'
- '8:-XX:NumberOfGCLogFiles=32'
- '1:-XX:CMSInitiatingOccupancyFraction=75'
```
by prefixing the options with the jvm version the options get "removed". see https://github.com/elastic/puppet-elasticsearch/issues/1032#issuecomment-642499082 and https://github.com/elastic/puppet-elasticsearch/issues/1053
