### ISSUE TITLE
Unable to autoload puppet/provider/elasticsearch_user_file/xpack on first catalog

### ISSUE THREAD

**Issue by sysadmin1139** [elastic/puppet-elasticsearch#1069]
* Module version: 6.4.0
* PuppetServer version: 5.3.10
* OS and version: Ubuntu 16.04

## Bug description
On the first compiled catalog after the puppetserver is reloaded, we're getting a series of errors and stack-traces.

```
2020-02-07 20:15:57,357 ERROR [qtp649028237-795] [puppetserver] Puppet Could not autoload puppet/provider/elasticsearch_user_file/xpack: no such file to load -- puppet/provider/elastic_parsedfile
org/jruby/RubyKernel.java:1040:in `require'
/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/puppet/code/modules/elasticsearch/lib/puppet/provider/elasticsearch_user_file/xpack.rb:1:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:1:in `(root)'
```

```
2020-02-07 20:15:57,381 ERROR [qtp649028237-795] [puppetserver] Puppet Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/xpack: no such file to load -- puppet/provider/elastic_parsedfile
org/jruby/RubyKernel.java:1040:in `require'
/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/opt/puppet/code/modules/elasticsearch/lib/puppet/provider/elasticsearch_user_file/xpack.rb:1:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:1:in `(root)'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load_file'
```

```
2020-02-07 20:15:57,384 ERROR [qtp649028237-795] [puppetserver] Puppet Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/xpack: no such file to load -- puppet/provider/elastic_parsedfile (file: /etc/puppetlabs/code/modules/elasticsearch/manifests/init.pp, line: 567, column: 6) on node 2002071944_ip-172-19-10-179.ec2.internal
2020-02-07 20:15:57,385 ERROR [qtp649028237-795] [puppetserver] Puppet Server Error: Evaluation Error: Error while evaluating a Virtual Query, Could not autoload puppet/type/elasticsearch_user_file: Could not autoload puppet/provider/elasticsearch_user_file/xpack: no such file to load -- puppet/provider/elastic_parsedfile (file: /etc/puppetlabs/code/modules/elasticsearch/manifests/init.pp, line: 567, column: 6) on node 2002071944_ip-172-19-10-179.ec2.internal
org/jruby/RubyKernel.java:1040:in `require'
/opt/puppetlabs/server/apps/puppetserver/jruby-1_7.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
/etc/puppetlabs/code/modules/elasticsearch/lib/puppet/provider/elasticsearch_user_file/xpack.rb:1:in `(root)'
org/jruby/RubyKernel.java:1059:in `load'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:1:in `(root)'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/autoload.rb:68:in `load_file'
```

The second and subsequent catalog-attempts will safely compile, it only impacts the very first one after a reload of the puppetserver (done after a code-push).

**Comment by neufeind** [comment]
Stumbled across this again, after upgrading to openvox-server 8.x. Where could that be an issue with loading-order (?).
