### ISSUE TITLE
Fact - ES version issue

### ISSUE THREAD

**Issue by eperdeme** [elastic/puppet-elasticsearch#488]
Hello,

Using this module on 2.0.0 ES RPM RHEL6.x I get the errors below from the facter ES version plugin, which then breaks the install

[root@cxpxelk02dat002 ~]# facter -p elasticsearch_version
Failed to configure logging...
ElasticsearchException[Failed to load logging configuration]; nested: NoSuchFileException[/usr/share/elasticsearch/config];
        at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:158)
        at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:103)
        at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:189)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:243)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config
        at sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
        at java.nio.file.Files.readAttributes(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.FileTreeWalker.walk(Unknown Source)
        at java.nio.file.Files.walkFileTree(Unknown Source)
        at org.elasticsearch.common.logging.log4j.LogConfigurator.resolveConfig(LogConfigurator.java:142)
        ... 4 more
log4j:WARN No appenders could be found for logger (bootstrap).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:92)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:138)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
2.0.0
[root@cxpxelk02dat002 ~]#

**Comment by electrical** [comment]
Hi,

I'm planning to remove this since there are more issues surrounding ES 2.0 support.
By the looks of it i will be doing a 1.0 release of the module that supports ES 1.x and a 2.0 of the module that supports ES 2.x

**Comment by eperdeme** [comment]
Oki Doki.

I think maybe a -V instead of a -v would return the value without ES trying to partially run before it is configured correctly.

**Comment by kraeuschen** [comment]
-V works fine.
