### ISSUE TITLE
Puppet module sees `bin/plugin exception` as a successful run

### ISSUE THREAD

**Issue by ntent-ashton** [elastic/puppet-elasticsearch#523]
I was working on what I *thought* was a clean system, but it turns out java-1.6.0-openjdk was installed.  Because ES doesn't like 1.6.0, bin/plugin fails with this message:
    
        [root@ca6-06:/usr/share/elasticsearch]# bin/plugin  http://nexus/nexus/content/repositories/releases/ntent/ntent-boilerplate/1.0.0/ntent-boilerplate-1.0.0.zip
    Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/plugins/PluginManagerCliParser : Unsupported major.minor version 51.0
    	at java.lang.ClassLoader.defineClass1(Native Method)
    	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
    	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
    	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
    	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
    	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
    	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
    
    Could not find the main class: org.elasticsearch.plugins.PluginManagerCliParser. Program will exit.

The elasticsearch module, however, registers: 

    Dec 15 09:17:52 ca6-06 puppet-agent[22029]: (/Stage[main]/Profiles::Elasticsearch::Plugins::Ntent-boilerplate/Elasticsearch::Plugin[ntent-boilerplate]/Exec[install_plugin_ntent-boilerplate]/returns) executed successfully
    Dec 15 09:17:52 ca6-06 puppet-agent[22029]: (/Stage[main]/Profiles::Elasticsearch::Plugins::Ntent-boilerplate/Elasticsearch::Plugin[ntent-boilerplate]/File[/usr/share/elasticsearch/plugins/ntent-boilerplate/.name]/ensure) change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /usr/share/elasticsearch/plugins/ntent-boilerplate/.name20151215-22029-1u4shbw.lock at 168:/etc/puppet/environments/production/modules/elasticsearch/manifests/plugin.pp

Replacing 1.6 with 1.8 resolved the issue, but the error reporting in this module is wrong.

**Comment by electrical** [comment]
Hi. I released a new version of the module that should handle this much better. 
Could you try that one ?

**Comment by ntent-ashton** [comment]
Oh yeah I can give the new module a shot.  Stand by.

**Comment by electrical** [comment]
Did it work as expected?

**Comment by ntent-ashton** [comment]
Sorry, I got derailed.  I'll test soon.

**Comment by electrical** [comment]
no worries. thanks!

**Comment by ntent-ashton** [comment]
Under identical circumstances, the new module version does in fact fail as expected, though not very explicitly.
http://fpaste.org/302883/65401145/

Changing Java version back to 1.8 resolved the issue.  Issue resolved - thanks!

**Comment by electrical** [comment]
I'll see if it's possible to get back the output from the command when it fails somehow.
