### ISSUE TITLE
start script tries to run ES instance as root

### ISSUE THREAD

**Issue by alexharv074** [elastic/puppet-elasticsearch#557]
Am I doing something wrong?

When I try to start the ES 2.0 instance on CentOS, after configuring with the latest version of the Puppet module:

```
[root@centos-66-x64 ~]# /etc/init.d/elasticsearch-es01 start
Starting elasticsearch:                                    [  OK  ]
[root@centos-66-x64 ~]# Exception in thread "main" java.lang.RuntimeException: don't run elasticsearch as root.
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:93)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:144)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
```

I see this thread here:
https://github.com/elastic/elasticsearch/issues/14458

**Comment by alexharv074** [comment]
This was my mistake.  An old init template was being passed in and I didn't know.
