### ISSUE TITLE
Missing CA File/Path Setting for Elasticsearch::Template Provider over HTTPS?

### ISSUE THREAD

**Issue by bflad** [elastic/puppet-elasticsearch#690]
* Module version: 0.13.2
* Puppet version: 4.6.1
* OS and version: Ubuntu 14.04

## Bug description

First off, thanks for the awesome module! Was excited to try out the fixed `elasticsearch::template` HTTPS support (I work with Petter from the last issue FYI), but looks like Puppet 4 might behave slightly different than Puppet 3 when it comes to the underlying Ruby OpenSSL. We use a DigiCert CA signed certificate on our Elasticsearch instances that works great outside the template provider (e.g. between nodes). The DigiCert CA certificate is in the normal /etc/ssl/certs directory for Ubuntu and already there by default, not a custom CA file or anything.

Turning off TLS verification in the Puppet module does work as a workaround, via: `elasticsearch::validate_tls: !!bool false`

With the default TLS verification, Elasticsearch rejects the Puppet provider request with:

```
Error: Failed to apply catalog: SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

```
[2016-08-29 19:29:02,469][WARN ][shield.transport.netty   ] [x-es-01] Caught exception while handling client http traffic, closing connection [id:
 0x32ee944e, /x.x.x.x:41649 => /x.x.x.x:9200]
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
        at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1218)
        at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:852)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.ipfilter.IpFilteringHandlerImpl.handleUpstream(IpFilteringHandlerImpl.java:154)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

With openssl on the command line we can see similar behavior where it cannot verify the CA:

```
echo | openssl s_client -connect $(hostname):9200
...
    Verify return code: 21 (unable to verify the first certificate)
```

However if we pass -CApath with Ubuntu's certificate directory to openssl, it verifies:

```
echo | openssl s_client -CApath /etc/ssl/certs -connect $(hostname):9200
...
    Verify return code: 0 (ok)
```

Do we need to provide someway to set the SSL CA file/path? I think by default in later versions of Ruby that OpenSSL may default to not trusting any CAs or something.

**Comment by tylerjl** [comment]
Hey @bflad, thanks for doing the legwork on this one. Definitely looks like the provider needs to accept an optional CA bundle to handle the case you've highlighted.

I think this could be solved pretty easily by just [calling `ca_file` on the `Net::HTTP` object in the provider](http://ruby-doc.org/stdlib-2.1.1/libdoc/net/http/rdoc/Net/HTTP.html) - there needs to be a `respond_to? :ca_file` for safety here, as Ruby ~1.8 doesn't expose the attribute accessor. But otherwise, it should permit us to control the CA bundle the HTTP request uses in versions of Ruby that can handle it.

The change should just be a matter of passing down a parameter from `elasticsearch::template` all the way down into the provider's ruby code (we probably also want to expose this as a top-level parameter on the `elasticsearch` class to make it easier to control for people with multiple instances, a lá `elasticsearch::api_ca_file` or something). If you get a chance, it would be useful to know whether `http.ca_file = '/etc/ssl/certs'` does fix your specific issue (it'd just need to be nearby the `use_ssl` calls in the code). Otherwise the fix may be more complicated.

If you want to take a crack at it, go for it, otherwise I'll try and get to this soon. 👍

**Comment by bflad** [comment]
Verified! Please note I used `http.ca_path` in my case so I didn't have to point to the specific CA file `/etc/ssl/certs/DigiCert_foobar.pem` or `/etc/ssl/certs/ca-certificates.crt`

```
--- /opt/puppetlabs/puppet/cache/lib/puppet/provider/elasticsearch_template/ruby.rb    	2016-08-29 20:28:28.878154908 +0000
+++ /tmp/puppet-file20160829-4215-1mn5q70      	2016-08-29 20:29:41.036900840 +0000
@@ -57,7 +57,7 @@
     req = Net::HTTP::Get.new uri.request_uri

     http.use_ssl = uri.scheme == 'https'
-    http.ca_file = '/etc/ssl/certs'
+    http.ca_path = '/etc/ssl/certs'

     response = rest http, req, validate_tls, timeout, username, password

@@ -123,7 +123,7 @@
     ])
     http = Net::HTTP.new uri.host, uri.port
     http.use_ssl = uri.scheme == 'https'
-    http.ca_file = '/etc/ssl/certs'
+    http.ca_path = '/etc/ssl/certs'

     case @property_flush[:ensure]
     when :absent

Notice: /File[/opt/puppetlabs/puppet/cache/lib/puppet/provider/elasticsearch_template/ruby.rb]/content: content changed '{md5}5251bcec001842a8085b79b0179cc19a' to '{md5}63d9ff21a69aaf9c40e4c6cec5746676'
```
