### ISSUE TITLE
Invalid resource type sysctl at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/config.pp:131:7 

### ISSUE THREAD

**Issue by chandankpathak** [elastic/puppet-elasticsearch#750]
* Module version:
* Puppet version:
* OS and version:

**Comment by chandankpathak** [comment]
While installing elastic search getting error as below:

Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Invalid resource type sysctl at /etc/puppetlabs/code/environments/production/modules/elasticsearch/manifests/config.pp:131:7 on node

Below is the config line 131

129 # Other OS than Linux may not have that sysctl
130 if $::kernel == 'Linux' {
131 sysctl { 'vm.max_map_count':
132 value => '262144',
133 }
134 }
135

What should we do?

System u=info is as bellow:

NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

**Comment by tylerjl** [comment]
Do you have the sysctl module installed?

**Comment by chandankpathak** [comment]
Yes we do have. below is the mod added in my puppetfile which is istalling sysctl module from puppet forge.


mod 'thias-sysctl', '1.0.6'


Still getting same error.


Regards

Chandan


________________________________

**Comment by tylerjl** [comment]
So, there's no other cause (that I can think of) other than puppet being unable to find the sysctl module that this error could be coming from, so you may want to try a few steps like making sure sysctl is in the right directory, restarting your puppetmaster if you're running in that type of environment, and so on.

Unfortunately there's nothing in this module that could be changed in order to resolve this issue, so I'm closing it, but I'll continue to respond if you need help with additional debugging steps.

**Comment by chandankpathak** [comment]
Hi Tyler,


That helped thanks for quick response. Elastic search is installed but its giving below error. Due to which service is crashing.


/var/log/elasticsearch/es-01/undef.log



[2016-12-08 15:30:53,450][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[2016-12-08 15:30:53,451][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-12-08 15:30:53,451][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2016-12-08 15:30:53,451][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example:


Any clue what may be the issue.

Regards

Chandan

________________________________

**Comment by tylerjl** [comment]
You may need to change some settings to permit Elasticsearch to start with the given memory settings on your particular machine. See [this stackoverflow answer](http://stackoverflow.com/a/18152957) as a starting point to resolve the issue.

**Comment by chandankpathak** [comment]
Thanks a lot.


Let me check it.


Regards

Chandan

________________________________

**Comment by chandankpathak** [comment]
Hi Tyler,


After following below step i am still getting error. Can you please guide me what shall i do.


/etc/security/limits.conf:

elasticsearch - nofile 65535
elasticsearch - memlock unlimited


/etc/default/elasticsearch (on CentOS/RH: /etc/sysconfig/elasticsearch ):

ES_HEAP_SIZE=512m
MAX_OPEN_FILES=65535
MAX_LOCKED_MEMORY=unlimited


/etc/elasticsearch/elasticsearch.yml:

bootstrap.mlockall: true



Error:


    at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)

[2016-12-09 13:46:45,324][WARN ][bootstrap                ] Unable to lock JVM Memory: error=12,reason=Cannot allocate memory
[2016-12-09 13:46:45,325][WARN ][bootstrap                ] This can result in part of the JVM being swapped out.
[2016-12-09 13:46:45,325][WARN ][bootstrap                ] Increase RLIMIT_MEMLOCK, soft limit: 65536, hard limit: 65536
[2016-12-09 13:46:45,325][WARN ][bootstrap                ] These can be adjusted by modifying /etc/security/limits.conf, for example:
    # allow user 'elasticsearch' mlockall
    elasticsearch soft memlock unlimited
    elasticsearch hard memlock unlimited
[2016-12-09 13:46:45,325][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2016-12-09 13:46:45,482][INFO ][node                     ] [use1appeesmnd20-es-01] version[2.4.2], pid[7025], build[161c65a/2016-11-17T11:51:03Z]
[2016-12-09 13:46:45,482][INFO ][node                     ] [use1appeesmnd20-es-01] initializing ...
[2016-12-09 13:46:45,940][INFO ][plugins                  ] [use1appeesmnd20-es-01] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2016-12-09 13:46:47,600][ERROR][bootstrap                ] Guice Exception: java.lang.IllegalArgumentException: Failed to resolve address for [use1appeesmnd21.na.corplan.net]
Likely root cause: java.net.UnknownHostException: use1appeesmnd21.na.corplan.net: Name or service not known
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)


Regards

Chandan

________________________________

**Comment by tylerjl** [comment]
The memory and limit messages are `WARN`, so they are just warnings, not errors halting node startup. The error in the log message is Elasticsearch's inability to contact another node you've passed it in the configuration, `use1appeesmnd21.na.corplan.net`.
