### ISSUE TITLE
Plugin resource reinstalls plugins on every Puppet run. 

### ISSUE THREAD

**Issue by thegrendle** [elastic/puppet-elasticsearch#936]
## Information
* Module version: 6.2.2
* Puppet version: 4.10.10
* OS and version: Redhat Enterprise Linux 6.9

## Bug description

Plugin resource reinstalls plugin(s) on every Puppet run. 

$elasticsearch_version = '6.2.4'

elasticsearch::plugin { "elasticsearch/x-pack/${elasticsearch_version}":
  url => "http://puppetrepo/elasticsearch/x-pack-${elasticsearch_version}.zip",
  instances => 'production',
}

[puppetrun.txt](https://github.com/elastic/puppet-elasticsearch/files/1995534/puppetrun.txt)
[puppetrun-debug.txt](https://github.com/elastic/puppet-elasticsearch/files/1995535/puppetrun-debug.txt)

**Comment by tylerjl** [comment]
Confirmed that the x-pack plugin descriptor file was changed and no longer contains the meta plugin version, so this will need to be updated. Thank you for the report!

**Comment by vchan2002** [comment]
I am seeing something that might be related, as I'm trying to install xpack for 6.2.2, but my puppet manifest is slightly different....as i am following the way this are setup in the README.....
  class { 'elasticsearch':
    manage_repo   => true,
    repo_version  => '6.x',
    version       => $esversion,
    config        => $config_hash,
    init_defaults => $init_hash,
    require       => Class['java'],
    security_plugin => 'x-pack',
  }
  elasticsearch::plugin { 'x-pack': instances => 'es-01' }

This is actually causing other plugins to not install properly and is breaking the installation.
`
Exception in thread "main" java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [.name]. Was the plugin built before 2.0?
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:352)
	at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:328)
	at org.elasticsearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:600)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:588)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:707)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:623)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:223)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:212)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:48)
Caused by: java.nio.file.FileSystemException: /usr/share/elasticsearch/plugins/x-pack/.name/plugin-descriptor.properties: Not a directory
`
