### ISSUE TITLE
scripts symlink causes startup failure

### ISSUE THREAD

**Issue by nambrosch** [elastic/puppet-elasticsearch#951]
when puppet installs a new instance, a scripts symlink is created which prevents elasticsearch from starting.  if i remove the scripts symlink then elasticsearch starts up fine.  is there a fix for this?

java error:
```
java.lang.IllegalStateException: security initialization failed
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:373) ~[?:?]
	at org.elasticsearch.node.Node.lambda$new$7(Node.java:405) ~[elasticsearch-6.3.0.jar:6.3.0]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267) ~[?:1.8.0_172]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_172]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_172]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_172]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_172]
	at org.elasticsearch.node.Node.<init>(Node.java:408) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.3.0.jar:6.3.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.3.0.jar:6.3.0]
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/etc/elasticsearch/01/scripts" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:1.8.0_172]
	at java.security.AccessController.checkPermission(AccessController.java:884) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549) ~[?:1.8.0_172]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888) ~[?:1.8.0_172]
	at sun.nio.fs.UnixPath.checkRead(UnixPath.java:795) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:290) ~[?:?]
	at java.nio.file.Files.exists(Files.java:2385) ~[?:1.8.0_172]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:157) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.createChild(FileWatcher.java:173) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.listChildren(FileWatcher.java:188) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.onDirectoryCreated(FileWatcher.java:299) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.init(FileWatcher.java:162) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher$FileObserver.access$000(FileWatcher.java:75) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.FileWatcher.doInit(FileWatcher.java:65) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.AbstractResourceWatcher.init(AbstractResourceWatcher.java:36) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.watcher.ResourceWatcherService.add(ResourceWatcherService.java:143) ~[elasticsearch-6.3.0.jar:6.3.0]
	at org.elasticsearch.xpack.security.authc.file.FileUserPasswdStore.<init>(FileUserPasswdStore.java:68) ~[?:?]
	at org.elasticsearch.xpack.security.authc.file.FileUserPasswdStore.<init>(FileUserPasswdStore.java:56) ~[?:?]
	at org.elasticsearch.xpack.security.authc.file.FileRealm.<init>(FileRealm.java:25) ~[?:?]
	at org.elasticsearch.xpack.security.authc.InternalRealms.lambda$getFactories$0(InternalRealms.java:96) ~[?:?]
	at org.elasticsearch.xpack.security.authc.Realms.addNativeRealms(Realms.java:237) ~[?:?]
	at org.elasticsearch.xpack.security.authc.Realms.initRealms(Realms.java:184) ~[?:?]
	at org.elasticsearch.xpack.security.authc.Realms.<init>(Realms.java:63) ~[?:?]
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:439) ~[?:?]
	at org.elasticsearch.xpack.security.Security.createComponents(Security.java:371) ~[?:?]
	... 20 more
```

symlink:
```
[root@centos3 manifests]# ls -Al /etc/elasticsearch/01/
total 24
-rw-rw---- 1 elasticsearch elasticsearch  207 Jun 14 20:17 elasticsearch.keystore
-r--r----- 1 elasticsearch elasticsearch  147 Jun 15 11:14 elasticsearch.yml
-rw-r--r-- 1 elasticsearch elasticsearch 1017 Jun 14 20:17 jvm.options
-rw-r--r-- 1 elasticsearch elasticsearch 4461 Jun 14 17:29 log4j2.properties
-rw-r--r-- 1 elasticsearch elasticsearch 1563 Jun 14 17:29 logging.yml
lrwxrwxrwx 1 elasticsearch elasticsearch   32 Jun 15 02:11 scripts -> /usr/share/elasticsearch/scripts
```

using centos 7.5
oracle jdk 8.172
elasticsearch 6.3.0
puppet agent 1.10.14
puppet module elastic-elasticsearch 6.2.2

**Comment by nambrosch** [comment]
oh here we go, it's been fixed but not part of the latest release, any idea when it will be?

https://github.com/elastic/puppet-elasticsearch/commit/b8a03690ae8d7da26e0c0776e56bf8cacb27b198

**Comment by tylerjl** [comment]
Went out today as part of the 6.3.0 release.

**Comment by gtsiou** [comment]
I still see this on 6.4.1 on Windows 10 host with an Ubuntu 16.04 VM. Should this be reported as a puppet issue maybe?

**Comment by tylerjl** [comment]
@gtsiou [currently, the module controls scripts as a directory in `/etc/elasticsearch`](https://github.com/elastic/puppet-elasticsearch/blob/6.3.3/manifests/config.pp#L64-L70), which is recursively copied into Elasticsearch instance directories later. What version of the Puppet module are you using, and is the scripts directory a symlink for you? The module isn't defining symlinks anywhere, so the behavior you're describing is unexpected.

**Comment by gtsiou** [comment]
@tylerjl I am using puppet-agent in 5.3. I see this is a bit outdated now so I will try with a latest version. Removing the symlink does fix the issues though, but I will try to nail down the software that causes this problem in this case since it does not seem to be related to puppet-elasticsearch.

**Comment by tylerjl** [comment]
Hi @marcinbojko, [this was fixed in module version 6.3.0](https://github.com/elastic/puppet-elasticsearch/releases/tag/6.3.0).

**Comment by marcinbojko** [comment]
You're right. For breaking change reason I couldn't switch to 6.x, but I've found e proper line in https://github.com/elastic/puppet-elasticsearch/blob/2be3574d9e063b821cf14339008053ea5e903b3a/manifests/instance.pp#L389 and good to go.

**Comment by glafir** [comment]
In 7.1.1 I have this error

**Comment by cr-liadsh** [comment]
Still happening in 6.8.6
